# Generated by Django 6.0.3 on 2026-04-28 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('gallery', '0001_initial'),
        ('gallery', '0002_message'),
        ('gallery', '0002_agent_agentnationality_classifier_department_and_more'),
        ('gallery', '0003_agent_agentnationality_classifier_department_and_more'),
        ('gallery', '0004_match_status_fields'),
        ('gallery', '0005_merge_20260424_1641'),
        ('gallery', '0006_reference_match_requested_by_match_seen_by_user1_and_more'),
        ('gallery', '0007_match_declined_status'),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("begin_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("begin_bce", models.BooleanField(blank=True, null=True)),
                ("end_bce", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "agents",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AgentNationality",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "agent",
                        "nationality",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "agents_nationalities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.TextField(blank=True, null=True)),
                (
                    "accession_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "objects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Classifier",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "classifiers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nationality",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("descriptor", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "nationalities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectClassifier",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "artwork",
                        "classifier",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "objects_classifiers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectDepartment",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "artwork",
                        "department",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "objects_departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ObjectPlace",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "artwork",
                        "place",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "objects_places",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("part_of", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "places",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "artwork",
                        "agent",
                        "part",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "productions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "references",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user1",
                        "user2",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("similarity", models.FloatField()),
                ("matched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("seen_by_user1", models.BooleanField(default=False)),
                ("seen_by_user2", models.BooleanField(default=False)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user1",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_user2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("like", "Like"), ("pass", "Pass")], max_length=10
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallery.artwork",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "artwork")},
            },
        ),
        migrations.CreateModel(
            name="TasteSignal",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user",
                        "facet",
                        "value",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facet", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=255)),
                ("like_count", models.IntegerField(default=0)),
                ("pass_count", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0.5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="gallery_tas_user_id_1ee02b_idx"
                    ),
                    models.Index(
                        fields=["facet", "value"], name="gallery_tas_facet_30d70f_idx"
                    ),
                ],
            },
        ),
    ]
