# Generated by Django 6.0.3 on 2026-04-10 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('begin_bce', models.BooleanField(blank=True, null=True)),
                ('end_bce', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentNationality',
            fields=[
                ('pk', models.CompositePrimaryKey('agent', 'nationality', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'agents_nationalities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'classifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'nationalities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectClassifier',
            fields=[
                ('pk', models.CompositePrimaryKey('artwork', 'classifier', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'objects_classifiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectDepartment',
            fields=[
                ('pk', models.CompositePrimaryKey('artwork', 'department', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'objects_departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectPlace',
            fields=[
                ('pk', models.CompositePrimaryKey('artwork', 'place', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'objects_places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('part_of', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('pk', models.CompositePrimaryKey('artwork', 'agent', 'part', blank=True, editable=False, primary_key=True, serialize=False)),
                ('part', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('pk', models.CompositePrimaryKey('user1', 'user2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('similarity', models.FloatField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TasteSignal',
            fields=[
                ('pk', models.CompositePrimaryKey('user', 'facet', 'value', blank=True, editable=False, primary_key=True, serialize=False)),
                ('facet', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('like_count', models.IntegerField(default=0)),
                ('pass_count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='gallery_tas_user_id_1ee02b_idx'), models.Index(fields=['facet', 'value'], name='gallery_tas_facet_30d70f_idx')],
            },
        ),
    ]
