# Generated by Django 6.0.3 on 2026-04-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_agent_agentnationality_classifier_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='seen_by_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='seen_by_user2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
